version: "3.8"

services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: bezkoder-app
    build: ./bezkoder-app
    restart: on-failure
    depends_on:
      - postgresdb
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:postgresql://postgresdb:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}",
          "spring.datasource.username": "${POSTGRESDB_USER}",
          "spring.datasource.password": "${POSTGRESDB_ROOT_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    volumes:
      - ~/.m2:/root/.m2

volumes:
  db_data:
